/*
	the format of the tree definition file is simple,
	you can find specification in the Tigra Menu documentation at:

	http://www.softcomplex.com/products/tigra_menu/docs/items.html
*/

var TREE_ITEMS1 = [
	['LIGA',null,
		['[Options]',null,
			['Title=LigaMaker Version 0.1',null],
			['Name=Liga Titel',null],
			['Type=0',null],
			['Teams=12',null],
			['vonTab=0',null],
			['bisTab=0',null],
			['Rounds=31',null],
			['Matches=7',null],
			['Actual=30',null],
			['Kegel=0',null],
			['HandS=0',null],
			['PointsForWin=2',null],
			['PointsForDraw=1',null],
			['PointsForLost=0',null],
			['Spez=0',null],
			['HideDraw=0',null],
			['OnRun=0',null],
			['MinusPoints=2',null],
			['Direct=0',null],
			['Champ=1',null],
			['CL=0',null],
			['CK=0',null],
			['UC=0',null],
			['AR=0',null],
			['AB=2',null],
			['namePkt=Pkt.',null],
			['nameTor=Tore',null],
			['DatC=1',null],
			['DatS=1',null],
			['DatM=1',null],
			['DatF=%a.%d.%m. %H:%M',null],
			['urlT=1',null],
			['urlB=0',null],
			['Graph=1',null],
			['Kreuz=1',null],
			['favTeam=0',null],
			['selTeam=0',null],
			['kurve1=0',null],
			['kurve2=0',null],
			['ticker=0',null],
			['dataSource=CSV-Import',null],
			['dataSourceUrl=',null],
		],
		['[Teams]',null,
			['1=SG Schorndorf 1846 2',null],
			['2=HSG Oberer Neckar 2',null],
			['3=Spvgg Möhringen 3',null],
			['4=VfL Waiblingen 3',null],
			['5=HSG Degerloch',null],
			['6=SV Fellbach 2',null],
			['7=HSG Weinstadt 3',null],
			['8=EK Stuttgart',null],
			['9=Hbi Weilimdorf/Feuerbach 2',null],
			['10=TV Bittenfeld 1898 3',null],
			['11=TSF Welzheim 2',null],
			['12=SV Stuttgarter Kickers 2',null],
		],
		['[Teamk]',null,
			['1=SG Sc',null],
			['2=HSG O',null],
			['3=Spvgg',null],
			['4=VfL W',null],
			['5=HSG D',null],
			['6=SV Fe',null],
			['7=HSG W',null],
			['8=EK St',null],
			['9=Hbi W',null],
			['10=TV Bi',null],
			['11=TSF W',null],
			['12=SV St',null],
		],
		['[Round31]',null,
			['D1=03.04.2004',null],
			['D2=04.04.2004',null],
			['TA1=3',null],
			['TB1=5',null],
			['GA1=-1',null],
			['GB1=-1',null],
			['AT1=1080997200',null],
			['NT1=',null],
			['TA2=7',null],
			['TB2=10',null],
			['GA2=-1',null],
			['GB2=-1',null],
			['AT2=1081067400',null],
			['NT2=',null],
			['TA3=1',null],
			['TB3=11',null],
			['GA3=-1',null],
			['GB3=-1',null],
			['AT3=1081076400',null],
			['NT3=',null],
			['TA4=9',null],
			['TB4=12',null],
			['GA4=-1',null],
			['GB4=-1',null],
			['AT4=1081078200',null],
			['NT4=',null],
			['TA5=6',null],
			['TB5=8',null],
			['GA5=-1',null],
			['GB5=-1',null],
			['AT5=1081081800',null],
			['NT5=',null],
		],
	],
];


var TREE_ITEMS2 = [
	['LIGA',null,
		['[Options]',null,
			['Title=LigaMaker Version 0.1',null],
			['Name=Liga Titel',null],
			['Type=0',null],
			['Teams=12',null],
			['vonTab=0',null],
			['bisTab=0',null],
			['Rounds=31',null],
			['Matches=7',null],
			['Actual=30',null],
			['Kegel=0',null],
			['HandS=0',null],
			['PointsForWin=2',null],
			['PointsForDraw=1',null],
			['PointsForLost=0',null],
			['Spez=0',null],
			['HideDraw=0',null],
			['OnRun=0',null],
			['MinusPoints=2',null],
			['Direct=0',null],
			['Champ=1',null],
			['CL=0',null],
			['CK=0',null],
			['UC=0',null],
			['AR=0',null],
			['AB=2',null],
			['namePkt=Pkt.',null],
			['nameTor=Tore',null],
			['DatC=1',null],
			['DatS=1',null],
			['DatM=1',null],
			['DatF=%a.%d.%m. %H:%M',null],
			['urlT=1',null],
			['urlB=0',null],
			['Graph=1',null],
			['Kreuz=1',null],
			['favTeam=0',null],
			['selTeam=0',null],
			['kurve1=0',null],
			['kurve2=0',null],
			['ticker=0',null],
			['dataSource=CSV-Import',null],
			['dataSourceUrl=',null],
		],
		['[Teams]',null,
			['1=SG Schorndorf 1846 2',null],
			['2=HSG Oberer Neckar 2',null],
			['3=Spvgg Möhringen 3',null],
			['4=VfL Waiblingen 3',null],
			['5=HSG Degerloch',null],
			['6=SV Fellbach 2',null],
			['7=HSG Weinstadt 3',null],
			['8=EK Stuttgart',null],
			['9=Hbi Weilimdorf/Feuerbach 2',null],
			['10=TV Bittenfeld 1898 3',null],
			['11=TSF Welzheim 2',null],
			['12=SV Stuttgarter Kickers 2',null],
		],
		['[Team7]',null,
			['Sp=0',null],
			['URL=',null],
			['NOT=',null],
		],
		['[Team8]',null,
			['Sp=0',null],
			['URL=',null],
			['NOT=',null],
		],
		['[Team9]',null,
			['Sp=0',null],
			['URL=',null],
			['NOT=',null],
		],
		['[Team10]',null,
			['Sp=0',null],
			['URL=',null],
			['NOT=',null],
		],
		['[Team11]',null,
			['Sp=0',null],
			['URL=',null],
			['NOT=',null],
		],
		['[Team12]',null,
			['Sp=0',null],
			['URL=',null],
			['NOT=',null],
		],
	],
];
		

